# -*- coding: utf-8 -*-
"""YouTubeAnalytics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iZSrd8HXkNU8gltM8b5087RmCatqh4oJ
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import datetime as dt
import plotly.express as px

df = pd.read_csv("/content/Global YouTube Statistics.csv" , encoding = 'latin1')

df.head()

df.tail()

df.sample(5)

df.info()

df.describe().round()

df.describe(include = 'object')

df.isna().sum()

df.isnull().sum()

df.duplicated().sum()

df.columns

print(df.columns)

df.dtypes

pd.set_option("display.float_format" , "{:0.2f}".format)

Category_subscriber_mean = df.groupby("category")['subscribers'].mean().head(6).reset_index()

Category_subscriber_mean

Category_subscriber_mean.sort_values(ascending = False)

px.bar(data_frame = Category_subscriber_mean , x = 'category' , y = 'subscribers' , text_auto = True , title = 'Category Per Subscriber')

plt.figure(figsize = (14 , 5))
sns.barplot(data = Category_subscriber_mean , x = 'category' , y = 'subscribers' , color = 'Purple')
plt.title('\nCategory Per Subscriber\n' , fontsize = 14 , fontweight = 'bold')
plt.xlabel('\nCategory\n' , fontsize = 12)
plt.ylabel('\nNumber of Subscriber\n' , fontsize = 12)
plt.grid(True , linestyle = '--' , alpha = 0.5)
plt.show()

df['channel_type'].value_counts()

df['channel_type'].unique()

df['channel_type'].nunique()

plt.figure(figsize = (14 , 5))
df['channel_type'].value_counts().plot(kind = 'bar')
plt.title('\nNumber of Channels\n' , fontsize = 14 , fontweight = 'bold')
plt.xlabel('\nChannel Name\n' , fontsize = 12)
plt.ylabel('\nNumber of Channels\n' , fontsize = 12)
plt.grid(True , linestyle = '--' , alpha = 0.5)
plt.show()

plt.figure(figsize = (14 , 5))
df['channel_type'].value_counts().head(3).plot(kind = 'pie' , autopct = '%1.1f%%' )
plt.title('\nNumber of Channels\n' , fontsize = 14 , fontweight = 'bold')
plt.show()

df.columns

plt.figure(figsize = (14 , 5))
plt.scatter(df['subscribers'] , df['video views'] , color = 'red')
plt.title('\nSubscriber VS YouTube Views\n' , fontsize = 14 , fontweight = 'bold')
plt.xlabel('\nSubscribers\n' , fontsize = 12)
plt.ylabel('\nYouTube Views\n' , fontsize = 12)
plt.grid(True , linestyle = '--' , alpha = 0.5)
plt.show()

Country_Subscribers = df.groupby('Country')['subscribers'].sum().head().sort_values(ascending = False)

Country_Subscribers

plt.figure(figsize = (14 , 5))
Country_Subscribers.plot(kind = 'bar' , color = 'gray')
plt.title('\nSubscriber VS YouTube Views\n' , fontsize = 14 , fontweight = 'bold')
plt.xlabel('\nSubscribers\n' , fontsize = 12)
plt.ylabel('\nYouTube Views\n' , fontsize = 12)
plt.grid(True , linestyle = '--' , alpha = 0.5)
plt.xticks(rotation = 0)
plt.show()

Yearly_subscribers = df.groupby('created_year' )['subscribers'].sum().reset_index()
Yearly_subscribers

px.line(data_frame = Yearly_subscribers , x = 'created_year' , y = 'subscribers' ,  title = 'Yearly Subscribers')

df.groupby('channel_type')['video_views_rank'].median().sort_values(ascending = False)

df.groupby('Country')['subscribers_for_last_30_days'].max().head().sort_values(ascending = False)

df.columns

Monthly_Subscribers = df.groupby('created_month' , as_index = False)['subscribers'].sum()

px.line(data_frame = Monthly_Subscribers , x = 'created_month' , y = 'subscribers' , text = 'subscribers')

df.groupby('category')['video views'].std()

df.groupby('Country')['Unemployment rate'].mean().head().sort_values(ascending = False)

df.groupby('channel_type')['uploads'].sum()

df.groupby(['Latitude' , 'Longitude']).size().head()

plt.figure(figsize = (14 , 5))
sns.boxplot( x = 'channel_type' , y = 'highest_monthly_earnings' , data = df , color = 'blue')
plt.title('\nDistribution of Heighest Montly Earnings\n' , fontsize = 14 , fontweight = 'bold')
plt.xlabel('\nChannel Type\n' , fontsize = 12)
plt.ylabel('\nDistribution\n' , fontsize = 12)
plt.grid(True , linestyle = '--' , alpha = 0.5)
plt.xticks(rotation = 45)
plt.show()

plt.figure(figsize = (14 , 5))
df.groupby(['category' , 'Country'])['subscribers'].sum().head(10).unstack().plot(kind = 'bar' , stacked = True)
plt.legend(title = 'Country' , bbox_to_anchor = (1.05 , 1) , loc = 'upper left')
plt.title('\nDistribution of Heighest Montly Earnings\n' , fontsize = 14 , fontweight = 'bold')
plt.xlabel('\nChannel Type\n' , fontsize = 12)
plt.ylabel('\nDistribution\n' , fontsize = 12)
plt.grid(True , linestyle = '--' , alpha = 0.5)
plt.xticks(rotation = 45)
plt.show()

df.columns

plt.figure(figsize = (14 , 5))
plt.scatter(df['Gross tertiary education enrollment (%)'] , df['subscribers'] , alpha = 0.5 , color = 'red')
plt.title('\nGross Tertiary Education Enrollment\n' , fontsize = 14 , fontweight = 'bold')
plt.xlabel('\neducation Enrollment\n' , fontsize = 12)
plt.ylabel('\nDistribution\n' , fontsize = 12)
plt.grid(True , linestyle = '--' , alpha = 0.5)
plt.xticks(rotation = 45)
plt.show()

plt.figure(figsize = (15 , 5))
df.groupby('channel_type')['Unemployment rate'].mean().plot(kind = 'bar')
plt.title('\nChannel Type by Employement Rate\n' , fontsize = 14 , fontweight = 'bold')
plt.xlabel('\nChannel Type\n' , fontsize = 12)
plt.ylabel('\nUnemployement Rate\n' , fontsize = 12)
plt.grid(True , linestyle = '--' , alpha = 0.5)
plt.xticks(rotation = 45)
plt.show()

df.columns

plt.figure(figsize = (15 , 6))
df.groupby(['created_date' , 'channel_type'])['subscribers'].mean().unstack().tail(3).plot(kind = 'bar' , width = 1)
plt.title('\nChannel Type by Employement Rate\n' , fontsize = 14 , fontweight = 'bold')
plt.xlabel('\nYear\n' , fontsize = 12)
plt.ylabel('\nSuscribers\n' , fontsize = 12)
plt.grid(True , linestyle = '--' , alpha = 0.5)
plt.legend(title = 'Channel Type' , bbox_to_anchor = (1.05 , 1) , loc = 'upper left')
plt.xticks(rotation = 0)
plt.show()

plt.figure(figsize = (15 , 6))
df.groupby(['created_year' , 'created_month'])['subscribers'].sum().unstack().head().plot(kind = 'area' , stacked = True)
plt.title('\nSubscribtion Growth Over Years\n' , fontsize = 14 , fontweight = 'bold')
plt.xlabel('\nYears\n' , fontsize = 12)
plt.ylabel('\nSuscribers\n' , fontsize = 12)
plt.grid(True , linestyle = '--' , alpha = 0.5)
plt.legend(title = 'Month Name' , bbox_to_anchor = (1.05 , 1) , loc = 'upper left')
plt.xticks(rotation = 0)
plt.show()

plt.figure(figsize = (15 , 6))
df.groupby(['created_year' , 'created_month'])['highest_yearly_earnings'].mean().unstack().head().plot(kind = 'line' , marker = 'o')
plt.title('\nHieghest Year Earnings\n' , fontsize = 14 , fontweight = 'bold')
plt.xlabel('\nYears\n' , fontsize = 12)
plt.ylabel('\nGrowth\n' , fontsize = 12)
plt.grid(True , linestyle = '--' , alpha = 0.5)
plt.legend(title = 'Month Name' , bbox_to_anchor = (1.05 , 1) , loc = 'upper left')
plt.xticks(rotation = 0)
plt.show()

df.columns

Category_Heighest_Earnings = df.groupby('category')['highest_monthly_earnings'].sum().head().reset_index()

plt.figure(figsize = (15 , 6))
Category_Heighest_Earnings.plot(kind = 'bar')
plt.title('\nHieghest Year Earnings Per Category\n' , fontsize = 14 , fontweight = 'bold')
plt.xlabel('\nCategory\n' , fontsize = 12)
plt.ylabel('\nHeighest Earnings\n' , fontsize = 12)
plt.grid(True , linestyle = '--' , alpha = 0.5)
plt.xticks(rotation = 0)
plt.show()

plt.figure(figsize = (20 , 5))
Category_Heighest_Earnings.plot(kind = 'bar')
plt.title('\nHieghest Year Earnings Per Category\n' , fontsize = 14 , fontweight = 'bold')
plt.xlabel('\nCategory\n' , fontsize = 12)
plt.ylabel('\nHeighest Earnings\n' , fontsize = 12)
plt.grid(True , linestyle = '--' , alpha = 0.5)
plt.xticks(rotation = 0)
plt.show()

px.bar(data_frame = Category_Heighest_Earnings , x = 'category' , y = 'highest_monthly_earnings' , text = 'highest_monthly_earnings' )

df.head()

Channeltypes = df.groupby('channel_type')['subscribers'].sum().head(3).reset_index()

Channeltypes.head().plot(kind = 'pie' , y = 'subscribers' , autopct = '%1.1f%%')
plt.title('\nChaneel Types\n' , fontsize = 14 , fontweight = 'bold')
plt.show()

Channel_Created = df.groupby(['channel_type' , 'created_year'])['subscribers_for_last_30_days'].mean().unstack()

Channel_Created

plt.figure(figsize = (15 , 6))
sns.heatmap(Channel_Created.head() , cmap = 'YlGnBu' , annot = False)
plt.title('\nMean Subscribers For the Last 30 Days\n' , fontsize = 14 , fontweight = 'bold')
plt.xlabel('\nYears\n' , fontsize = 12)
plt.ylabel('\nChannels\n' , fontsize = 12)
plt.show()

df.head(2)

Corr = [['subscribers' , 'video views' , 'uploads' , 'Unemployment rate']]

corr = df.corr(numeric_only=True)

plt.figure(figsize = (15 , 6))
sns.heatmap(corr , cmap = 'YlGnBu' , annot = False)
plt.title('\nCorrelation Test\n' , fontsize = 14 , fontweight = 'bold')
#plt.xlabel('\nYears\n' , fontsize = 12)
#plt.ylabel('\nChannels\n' , fontsize = 12)
plt.show()

x = df.groupby('created_month')['subscribers_for_last_30_days'].mean().reset_index()

plt.figure(figsize = (15 , 6))
x.plot(kind = 'line' , marker = 'o' , linestyle = '--')
plt.show()

df.head()

def Categorical_Date(x):
  print(df[x].nunique())
  print('==========================================================')
  print(df[x].unique())
  print('==========================================================')
  print(df[x].value_counts().head())
  print('==========================================================')
  plt.figure(figsize = (15 , 6))
  print(df[x].value_counts().head().plot(kind = 'bar' , color = 'orange'))
  plt.title( f'Distribution of {x}' , fontsize = 14 , fontweight = 'bold')
  plt.xlabel( x , fontsize = 12)
  plt.ylabel('\nFrequency\n' , fontsize = 12)
  plt.grid(True , linestyle = '--' , alpha = 0.5)
  plt.xticks(rotation = 0)

Categorical_Date('Country')

Categorical_Date('category')

Categorical_Date('channel_type')

Categorical_Date('created_month')

